version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers
    steps:
      - checkout
      - add_ssh_keys:  # add key from CircleCI account based on fingerprint
          fingerprints:
            - "7f:ba:32:20:68:73:d7:11:59:fb:6f:23:9c:3a:bf:32"
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: login server
          command: 
            ssh -o StrictHostKeyChecking=no 172.96.208.180
            ssh -v root@172.96.208.180 -p 26435
